# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: YoOnseO's PAGE
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Yunseo Choi.
baseurl: "/blog-demo" # the subpath of the site
url: "https://yoonseo1014.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.JPG
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: a50149191@gmail.com
      link: mailto:a50149191@gmail.com

  follow:
    - name: Facebook
      link: http://facebook.com/01037861322
    - name: GitHub
      link: http://github.com/Yoonseo1014
    #- name: RSS
    #  link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
